.TH NEOSC-APPSELECT "1" "April 2015" "" ""
.SH NAME
neosc-appselect \- allows you to switch to a specified YubiKey NEO(-N) applet
.SH SYNOPSIS
.B neosc-appselect
[\fIOPTION\fR]...
.SH DESCRIPTION
.PP
neosc-appselect is a tool that allows you to switch to a specified applet on a YubiKey NEO(-N).  This helps you to return the YubiKey to a state applications using the YubiKey and not being aware that a token may offer mutiple applets (i.e. nearly every application.
.TP
\fB\-N\fR
select NEO applet
.TP
\fB\-d\fR
select NDEF applet
.TP
\fB\-o\fR
select OATH applet
.TP
\fB\-O\fR
select OpenPGP applet
.TP
\fB\-P\fR
select PIV applet
.TP
\fB\-s\fR \fB\fIserial\fR\fR
use YubiKey with given serial number
.TP
\fB\-u\fR
use first USB attached YubiKey without serial number
.TP
\fB\-n\fR
use first NFC attached YubiKey
.TP
\fB\-U\fR
use first U2F enabled YubiKey 4 (nano)
.TP
\fB\-C\fR
use first U2F disabled YubiKey 4 (nano)
.TP
\fB\-h\fR
show help
.SH AUTHOR
Written by Andreas Steinmetz
.SH COPYRIGHT
Copyright \(co 2015 Andreas Steinmetz
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
